services:
  - type: web
    name: mini-team-chat-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
  - type: static
    name: mini-team-chat-frontend
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mini-team-chat-application-8.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://mini-team-chat-application-8.onrender.com
